### ISSUE TITLE
Lack of canary domains

### ISSUE THREAD

**Issue by VibroAxe** [jpgpi250/piholemanual#15]
Excellent write up on blocking DoH within PFSense however I note that the RPZ domain file doesn't include the firefox/apple canary domains?

**Comment by jpgpi250** [comment]
That is correct. they aren't (o)DoH domains, they are canary domains, which are meant to give administrators (some) control over whether or not (o)DoH is allowed when using firefox / apple.

If you want to ensure the canary domains provide the desired reply (NXDOMAIN), add a configuration file, for unbound that would be:
/etc/unbound/unbound.conf.d/canary.conf:
```
# canary domains
server:
        local-zone: "use-application-dns.net." always_nxdomain
        local-zone: "mask.icloud.com." always_nxdomain
        local-zone: "mask-h2.icloud.com." always_nxdomain
```
